### ISSUE TITLE
How to fix this error:

### ISSUE THREAD

**Issue by thecao365** [mehtadone/CryptoGramBot#5]
How to fix this error:

An error occurred when I used Bittrex commands

/trex_btc_balance - bittrex account summar

Please help me fix this!

>2017-10-17 15:41:55.330 +07:00 [Error] Woops. System.Exception: Request failed: INVALID_MARKET
   at BittrexSharp.Bittrex.<request>d__13.MoveNext() in C:\projects\telecoinigy\BittrexSharp\Bittrex.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BittrexSharp.Bittrex.<GetTicker>d__24.MoveNext() in C:\projects\telecoinigy\BittrexSharp\Bittrex.cs:line 246
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CryptoGramBot.Services.Exchanges.BittrexService.<GetPrice>d__10.MoveNext() in C:\projects\telecoinigy\CryptoGramBot\Services\Exchanges\BittrexService.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CryptoGramBot.Services.Exchanges.BittrexService.<GetBalance>d__5.MoveNext() in C:\projects\telecoinigy\CryptoGramBot\Services\Exchanges\BittrexService.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CryptoGramBot.EventBus.Handlers.Bittrex.BittrexBalanceCheckHandler.<Handle>d__4.MoveNext() in C:\projects\telecoinigy\CryptoGramBot\EventBus\Handlers\Bittrex\BittrexBalanceCheckHandler.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Enexure.MicroBus.EventHandlerShim`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Enexure.MicroBus.PipelineRunBuilder.<RunTasks>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Enexure.MicroBus.PipelineRunBuilder.<RunHandlers>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Enexure.MicroBus.PipelineRunBuilder.<>c__DisplayClass7_0.<<BuildNextHandler>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Enexure.MicroBus.MicroBus.<RunPipelineAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CryptoGramBot.Services.Telegram.TelegramMessageSendingService.<BittrexBalance>d__3.MoveNext() in C:\projects\telecoinigy\CryptoGramBot\Services\Telegram\TelegramMessageSendingService.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CryptoGramBot.Services.Telegram.TelegramMessageRecieveService.<CheckMessage>d__12.MoveNext() in C:\projects\telecoinigy\CryptoGramBot\Services\Telegram\TelegramMessageRecieveService.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CryptoGramBot.Services.Telegram.TelegramMessageRecieveService.<BotOnMessageReceivedAsync>d__10.MoveNext() in C:\projects\telecoinigy\CryptoGramBot\Services\Telegram\TelegramMessageRecieveService.cs:line 83
2017-10-17 15:41:55.629 +07:00 [Information] Send Message:
Could not process your command. Check your logs
2017-10-17 15:43:10.180 +07:00 [Information] 24 Hour pnl difference for bittrex
2017-10-17 15:43:11.953 +07:00 [Error] Woops. System.Exception: Request failed: INVALID_MARKET
   at BittrexSharp.Bittrex.<request>d__13.MoveNext() in C:\projects\telecoinigy\BittrexSharp\Bittrex.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BittrexSharp.Bittrex.<GetTicker>d__24.MoveNext() in C:\projects\telecoinigy\BittrexSharp\Bittrex.cs:line 246
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CryptoGramBot.Services.Exchanges.BittrexService.<GetPrice>d__10.MoveNext() in C:\projects\telecoinigy\CryptoGramBot\Services\Exchanges\BittrexService.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CryptoGramBot.Services.Exchanges.BittrexService.<GetBalance>d__5.MoveNext() in C:\projects\telecoinigy\CryptoGramBot\Services\Exchanges\BittrexService.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CryptoGramBot.EventBus.Handlers.Bittrex.BittrexBalanceCheckHandler.<Handle>d__4.MoveNext() in C:\projects\telecoinigy\CryptoGramBot\EventBus\Handlers\Bittrex\BittrexBalanceCheckHandler.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Enexure.MicroBus.EventHandlerShim`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Enexure.MicroBus.PipelineRunBuilder.<RunTasks>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Enexure.MicroBus.PipelineRunBuilder.<RunHandlers>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Enexure.MicroBus.PipelineRunBuilder.<>c__DisplayClass7_0.<<BuildNextHandler>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Enexure.MicroBus.MicroBus.<RunPipelineAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CryptoGramBot.Services.Telegram.TelegramMessageSendingService.<BittrexBalance>d__3.MoveNext() in C:\projects\telecoinigy\CryptoGramBot\Services\Telegram\TelegramMessageSendingService.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CryptoGramBot.Services.Telegram.TelegramMessageRecieveService.<CheckMessage>d__12.MoveNext() in C:\projects\telecoinigy\CryptoGramBot\Services\Telegram\TelegramMessageRecieveService.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CryptoGramBot.Services.Telegram.TelegramMessageRecieveService.<BotOnMessageReceivedAsync>d__10.MoveNext() in C:\projects\telecoinigy\CryptoGramBot\Services\Telegram\TelegramMessageRecieveService.cs:line 83
2017-10-17 15:43:12.243 +07:00 [Information] Send Message:
Could not process your command. Check your logs

**Comment by mehtadone** [comment]
This seems to be an issue with having a balance in a coin that has been delisted. 

I've added a fix for this in the latest version.
