### ISSUE TITLE
Error received Conflict: terminated by other  - long poll or webhook and getUpdates request

### ISSUE THREAD

**Issue by boshoffm** [mehtadone/CryptoGramBot#76]
Hope you can help with a solution.

I upgraded to the new version v0.3.291 and everything ran fine without any problems.

Then the last few days i have been receiving the following errors

First i received the below errors

2018-02-13 20:34:32.277 -08:00 [Error] Error received Conflict: terminated by other long poll or webhook
2018-02-13 20:34:34.750 -08:00 [Error] Error received Conflict: terminated by other long poll or webhook
2018-02-13 20:34:36.440 -08:00 [Error] Error received Conflict: terminated by other long poll or webhook

Now that error has been replaced with this one

2018-02-14 20:40:18.960 -08:00 [Error] Error received Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2018-02-14 20:40:24.205 -08:00 [Error] Error received Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2018-02-14 20:40:28.671 -08:00 [Error] Error received Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

I am not sure what is causing this. I only have one instance running, have rebooted and still i get the errors. I changed the port and updated the firewall. Time is synced so i am at a loss of what is causing this.

The exchange i am using is Bittrex. But my friend is facing the same problems and he is using Binance.

I really hope you could provide a solution.

**Comment by Escaflownevan** [comment]
same for me..

**Comment by juato4** [comment]
Same here!

**Comment by votetopovorot** [comment]
same for me too!

**Comment by zhongfly** [comment]
same!
but I want ask:is it mean one pc only can run one bot?
I try to run two bot with different botnames ,so got this:

2018-03-05 21:25:20,405 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-03-05 21:25:20,421 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception...
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telegram\ext\updater.py", line 312, in _network_loop_retry
    if not action_cb():
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telegram\ext\updater.py", line 273, in polling_action_cb
    allowed_updates=allowed_updates)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telegram\bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telegram\bot.py", line 1768, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telegram\utils\request.py", line 273, in post
    **urlopen_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telegram\utils\request.py", line 220, in _request_wrapper
    raise NetworkError('{0} ({1})'.format(message, resp.status))
telegram.error.NetworkError: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-03-05 21:25:26,605 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)

**Comment by ArchAL85** [comment]
Same for me too! Is it any solution?

**Comment by mehtadone** [comment]
Have you upgraded to the latest version?
