### ISSUE TITLE
crash under linux because of windows paths

### ISSUE THREAD

**Issue by jakkie** [mehtadone/CryptoGramBot#77]
When installing the latest version 0.3.291 under ubuntu linux, the app doesn't load because works with wrong windows paths. Below is what shown in bash.

Application startup exception: System.InvalidOperationException: Failed to convert 'INSERT HERE' to type 'System.Int64'. ---> System.Exception: INSERT HERE is not a valid value for Int64. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.ComponentModel.Int64Converter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.TryConvertValue(Type type, String value, Object& result, Exception& error)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance)
   at CryptoGramBot.Startup.ConfigureConfig(IContainer container, IConfiguration configuration, ILogger`1 log) in **C:\projects\telecoinigy\CryptoGramBot\Startup.cs:line 195**
   at CryptoGramBot.Startup.ConfigureServices(IServiceCollection services) in **C:\projects\telecoinigy\CryptoGramBot\Startup.cs:line 154**
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
[09:36:12 FTL] Application startup exception
System.InvalidOperationException: Failed to convert 'INSERT HERE' to type 'System.Int64'. ---> System.Exception: INSERT HERE is not a valid value for Int64. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.ComponentModel.Int64Converter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.TryConvertValue(Type type, String value, Object& result, Exception& error)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance)
   at CryptoGramBot.Startup.ConfigureConfig(IContainer container, IConfiguration configuration, ILogger 1 log) in **C:\projects\telecoinigy\CryptoGramBot\Startup.cs:line 195**
   at CryptoGramBot.Startup.ConfigureServices(IServiceCollection services) in **C:\projects\telecoinigy\CryptoGramBot\Startup.cs:line 154**
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

**Comment by gambcl** [comment]
This is nothing to do with windows paths, you have forgotten to provide your Telegram ChatID in the appsettings.json file.
If you read the error message, it is complaining that it is looking for a number and instead it found "INSERT HERE".
You need to fill in your details properly in the appsettings.json file before it will work.
