### ISSUE TITLE
System.AggregateException: One or more errors occurred

### ISSUE THREAD

**Issue by Nader-Alabed** [mehtadone/CryptoGramBot#82]
Dear Sir,

the bot is installed on (ubuntu server 17.10 VPS) and linked with bittrex account it is stopped before 14 days, below the terminal return, I tried versions (0.3.298 , 0.3.300 and 0.3.302) same issue.

---------------------------------------------------------------------------------------------------------
Linux package/CryptoGramBot$ dotnet  CryptoGramBot.dll
[12:40:23 INF] Services
Coinigy: False
Bittrex: True
Binance: False
Poloniex: False
[12:40:23 INF] Created coinigy config
[12:40:23 INF] Created general config
[12:40:23 INF] Created telegram config
[12:40:23 INF] Created bittrex Config
[12:40:23 INF] Created binance config
[12:40:23 INF] Created poloniex config
[12:40:26 ERR] Could not send message. Invalid chat id
Response status code does not indicate success: 404 (Not Found).

Unhandled Exception: Hosting environment: Production
Content root path: /home/nadercrypto/Gunbot XT Edition - Linux package/CryptoGramBot
Now listening on: http://localhost:6005
Application started. Press Ctrl+C to shut down.
System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).) ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__124`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CryptoGramBot.Services.TelegramBot.<SendHtmlMessage>d__10.MoveNext() in C:\projects\telecoinigy\CryptoGramBot\Services\Telegram\TelegramBot.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CryptoGramBot.EventBus.Handlers.SendMessageHandler.<Handle>d__4.MoveNext() in C:\projects\telecoinigy\CryptoGramBot\EventBus\Handlers\SendMessageHandler.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Enexure.MicroBus.CommandHandlerShim`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Enexure.MicroBus.PipelineRunBuilder.<RunTasks>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Enexure.MicroBus.PipelineRunBuilder.<RunHandlers>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Enexure.MicroBus.PipelineRunBuilder.<>c__DisplayClass7_0.<<BuildNextHandler>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Enexure.MicroBus.MicroBus.<RunPipelineAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CryptoGramBot.Services.StartupCheckingService.<SendStartupMessage>d__16.MoveNext() in C:\projects\telecoinigy\CryptoGramBot\Services\StartupCheckingService.cs:line 156
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at CryptoGramBot.Services.StartupCheckingService.Start() in C:\projects\telecoinigy\CryptoGramBot\Services\StartupCheckingService.cs:line 113
   at CryptoGramBot.Startup.<OnStarting>d__13.MoveNext() in C:\projects\telecoinigy\CryptoGramBot\Startup.cs:line 265
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CryptoGramBot.Startup.<<Configure>b__9_0>d.MoveNext() in C:\projects\telecoinigy\CryptoGramBot\Startup.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted (core dumped)
---------------------------------------------------------------------------------------------------------

**Comment by Concept211** [comment]
I'm having the exact same issue. I've tried multiple versions of the bot, I've opened up the port on my firewall and router, etc. It used to work fine but now it has been a couple of weeks or so where it no longer works. I also verified that the bot and chat IDs are correct. Is there any way to fix this??

**Comment by Concept211** [comment]
Just to note: my issue above is on a Windows machine.
